#pragma once

#include "block.h"
#include "break_stmt.h"
#include "const_stmt.h"
#include "continue_stmt.h"
#include "decl_stmt.h"
#include "expr_stmt.h"
#include "for_stmt.h"
#include "func.h"
#include "if_stmt.h"
#include "print_stmt.h"
#include "return_stmt.h"
#include "stmt.h"
#include "type_stmt.h"
#include "while_stmt.h"
